import 'controller/sign_up_two_controller.dart';import 'package:flutter/material.dart';import 'package:vibra_verve/core/app_export.dart';import 'package:vibra_verve/core/utils/validation_functions.dart';import 'package:vibra_verve/widgets/app_bar/appbar_leading_image.dart';import 'package:vibra_verve/widgets/app_bar/appbar_subtitle_three.dart';import 'package:vibra_verve/widgets/app_bar/custom_app_bar.dart';import 'package:vibra_verve/widgets/custom_elevated_button.dart';import 'package:vibra_verve/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SignUpTwoScreen extends GetWidget<SignUpTwoController> {SignUpTwoScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: appTheme.gray10003, body: Form(key: _formKey, child: SizedBox(width: double.maxFinite, child: Column(children: [_buildNavbar(), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 29.v), child: Column(children: [_buildNewPasswordStack(), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Text("msg_atleast_1_number".tr, style: CustomTextStyles.titleSmallGray50001)), SizedBox(height: 30.v), CustomElevatedButton( onPressed: (){Get.toNamed('/login_screen');}, height: 48.v, text: "lbl_confirm".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL10, buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer17), SizedBox(height: 5.v)]))]))))); }
/// Section Widget
Widget _buildNavbar() { return Container(padding: EdgeInsets.symmetric(vertical: 3.v), decoration: AppDecoration.fillOnErrorContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 20.v), CustomAppBar(height: 26.v, leadingWidth: 36.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftPrimary, margin: EdgeInsets.only(left: 16.h, top: 3.v, bottom: 2.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitleThree(text: "lbl_back".tr, margin: EdgeInsets.only(left: 5.h))), SizedBox(height: 9.v), Text("lbl_new_password".tr, style: CustomTextStyles.titleMediumGray900)])); } 
/// Section Widget
Widget _buildNewPasswordStack() { return SizedBox(height: 128.v, width: 343.h, child: Stack(alignment: Alignment.topCenter, children: [CustomTextFormField(width: 343.h, controller: controller.newpasswordController, hintText: "msg_confirm_new_password".tr, textInputType: TextInputType.visiblePassword, alignment: Alignment.bottomCenter, validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: true, borderDecoration: TextFormFieldStyleHelper.outlineGray, filled: false), Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, children: [Obx(() => CustomTextFormField(controller: controller.newpasswordController1, hintText: "msg_enter_new_password2".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(12.h, 23.v, 22.h, 23.v), child: CustomImageView(imagePath: ImageConstant.imgContrastGray40002, height: 10.v, width: 17.h))), suffixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: controller.isShowPassword.value, contentPadding: EdgeInsets.only(left: 16.h, top: 15.v, bottom: 15.v), borderDecoration: TextFormFieldStyleHelper.outlineGray, filled: false)), SizedBox(height: 37.v), Align(alignment: Alignment.centerRight, child: Opacity(opacity: 0.9, child: Container(height: 14.v, width: 17.h, margin: EdgeInsets.only(right: 22.h), child: Stack(alignment: Alignment.centerRight, children: [Align(alignment: Alignment.center, child: SizedBox(height: 10.v, width: 17.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgContrastGray40002, height: 10.v, width: 17.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgContrastGray400026x7, height: 6.v, width: 7.h, radius: BorderRadius.circular(3.h), alignment: Alignment.center)]))), CustomImageView(imagePath: ImageConstant.imgSettingsGray40002, height: 14.adaptSize, width: 14.adaptSize, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 1.h))]))))]))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
