import 'controller/add_address_one_controller.dart';import 'package:flutter/material.dart';import 'package:vibra_verve/core/app_export.dart';import 'package:vibra_verve/widgets/app_bar/appbar_subtitle_seven.dart';import 'package:vibra_verve/widgets/app_bar/appbar_title_image.dart';import 'package:vibra_verve/widgets/app_bar/custom_app_bar.dart';import 'package:vibra_verve/widgets/custom_drop_down.dart';import 'package:vibra_verve/widgets/custom_elevated_button.dart';import 'package:vibra_verve/widgets/custom_text_form_field.dart';class AddAddressOneScreen extends GetWidget<AddAddressOneController> {const AddAddressOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 15.v), child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(children: [_buildCountry(), SizedBox(height: 23.v), _buildFirstName(), SizedBox(height: 23.v), _buildLastName(), SizedBox(height: 23.v), _buildStreetAddress(), SizedBox(height: 23.v), Align(alignment: Alignment.centerLeft, child: Text("msg_street_address_2".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 12.v), CustomTextFormField(controller: controller.streetaddressController1, textInputAction: TextInputAction.done), SizedBox(height: 24.v), _buildAddAddress(), SizedBox(height: 84.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_zip_code".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 84.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_phone_number".tr, style: theme.textTheme.titleSmall))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 123.v, centerTitle: true, title: Padding(padding: EdgeInsets.only(top: 70.v), child: Column(children: [Padding(padding: EdgeInsets.only(left: 16.h, right: 214.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeftBlueGray300, onTap: () {onTapArrowLeft();}), AppbarSubtitleSeven(text: "lbl_add_address".tr, margin: EdgeInsets.only(left: 12.h))])), SizedBox(height: 27.v), SizedBox(width: double.maxFinite, child: Divider())])), styleType: Style.bgFill_3); } 
/// Section Widget
Widget _buildCountry() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_country_or_region".tr, style: theme.textTheme.titleSmall), SizedBox(height: 11.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 16.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgSystemIcon24pxBottom, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_united_states".tr, items: controller.addAddressOneModelObj.value.dropdownItemList!.value, onChanged: (value) {controller.onSelected(value);})]); } 
/// Section Widget
Widget _buildFirstName() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_first_name".tr, style: theme.textTheme.titleSmall), SizedBox(height: 12.v), CustomTextFormField(controller: controller.firstNameController)]); } 
/// Section Widget
Widget _buildLastName() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_last_name".tr, style: theme.textTheme.titleSmall), SizedBox(height: 12.v), CustomTextFormField(controller: controller.lastNameController)]); } 
/// Section Widget
Widget _buildStreetAddress() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_street_address".tr, style: theme.textTheme.titleSmall), SizedBox(height: 12.v), CustomTextFormField(controller: controller.streetaddressController)]); } 
/// Section Widget
Widget _buildAddAddress() { return SizedBox(height: 124.v, width: 343.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_city".tr, style: theme.textTheme.titleSmall), SizedBox(height: 11.v), Container(height: 48.v, width: 343.h, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer.withOpacity(1), borderRadius: BorderRadius.circular(5.h), border: Border.all(color: appTheme.blue50, width: 1.h)))])), Align(alignment: Alignment.bottomLeft, child: Text("msg_state_province_region".tr, style: theme.textTheme.titleSmall)), CustomElevatedButton(width: 343.h, text: "lbl_add_address".tr, margin: EdgeInsets.only(bottom: 2.v), alignment: Alignment.bottomCenter)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
