import 'controller/notification_offer_controller.dart';import 'package:flutter/material.dart';import 'package:vibra_verve/core/app_export.dart';import 'package:vibra_verve/widgets/app_bar/appbar_leading_image.dart';import 'package:vibra_verve/widgets/app_bar/appbar_subtitle_four.dart';import 'package:vibra_verve/widgets/app_bar/custom_app_bar.dart';class NotificationOfferScreen extends GetWidget<NotificationOfferController> {const NotificationOfferScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [Divider(), _buildOfferList01(), _buildOfferList02(), SizedBox(height: 5.v), _buildOfferList03()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray300, margin: EdgeInsets.only(left: 16.h, top: 26.v, bottom: 28.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitleFour(text: "lbl_notification".tr, margin: EdgeInsets.only(left: 12.h)), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildOfferList01() { return Container(width: double.maxFinite, padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillOnErrorContainer, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSort, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 50.v)), Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_the_best_title".tr, style: CustomTextStyles.titleSmallBold), SizedBox(height: 10.v), Text("msg_tma_2hd_wireless2".tr, style: CustomTextStyles.bodySmallGray90001_1), SizedBox(height: 11.v), Text("msg_april_30_2014_1_01".tr, style: CustomTextStyles.bodySmallBlack90010)]))])); } 
/// Section Widget
Widget _buildOfferList02() { return Container(width: double.maxFinite, padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillOnErrorContainer, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSort, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 72.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_summer_offer_98".tr, style: CustomTextStyles.titleSmallBold), SizedBox(height: 10.v), SizedBox(width: 298.h, child: Text("msg_the_speaker_unit2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallGray90001_1.copyWith(height: 1.80))), SizedBox(height: 5.v), Text("msg_april_30_2014_1_01".tr, style: CustomTextStyles.bodySmallBlack90010)])))])); } 
/// Section Widget
Widget _buildOfferList03() { return Container(width: double.maxFinite, padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillOnErrorContainer, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSort, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 116.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_special_offer_25".tr, style: CustomTextStyles.titleSmallBold), SizedBox(height: 9.v), SizedBox(width: 303.h, child: Text("msg_the_speaker_unit3".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallGray90001_1.copyWith(height: 1.80))), SizedBox(height: 6.v), Text("msg_april_30_2014_1_01".tr, style: CustomTextStyles.bodySmallBlack90010)])))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
