import 'controller/change_password_wrong_controller.dart';import 'package:flutter/material.dart';import 'package:vibra_verve/core/app_export.dart';import 'package:vibra_verve/core/utils/validation_functions.dart';import 'package:vibra_verve/widgets/app_bar/appbar_leading_image.dart';import 'package:vibra_verve/widgets/app_bar/appbar_subtitle_four.dart';import 'package:vibra_verve/widgets/app_bar/custom_app_bar.dart';import 'package:vibra_verve/widgets/custom_elevated_button.dart';import 'package:vibra_verve/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class ChangePasswordWrongScreen extends GetWidget<ChangePasswordWrongController> {ChangePasswordWrongScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: SizedBox(width: double.maxFinite, child: Column(children: [Divider(), SizedBox(height: 14.v), _buildOldPassword(), SizedBox(height: 22.v), _buildNewPassword(), SizedBox(height: 24.v), _buildNewPasswordAgain(), SizedBox(height: 5.v)]))), bottomNavigationBar: _buildSave())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray300, margin: EdgeInsets.only(left: 16.h, top: 26.v, bottom: 28.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitleFour(text: "lbl_change_password".tr, margin: EdgeInsets.only(left: 12.h)), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildOldPassword() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_old_password".tr, style: CustomTextStyles.titleSmallIndigo900_1), SizedBox(height: 12.v), SizedBox(height: 75.v, width: 343.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.center, child: Container(decoration: AppDecoration.outlineLightBlueA, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 26.v), CustomTextFormField(controller: controller.passwordController, hintText: "msg".tr, hintStyle: theme.textTheme.labelLarge!, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 12.v, 10.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgLocationOnprimarycontainer, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 48.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: true, contentPadding: EdgeInsets.only(top: 15.v, right: 30.h, bottom: 15.v), borderDecoration: TextFormFieldStyleHelper.outlineOnPrimaryContainer, filled: false)]))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Text("msg_oops_your_password".tr, style: CustomTextStyles.labelLargeOnPrimaryContainer)))]))])); } 
/// Section Widget
Widget _buildNewPassword() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_new_password2".tr, style: CustomTextStyles.titleSmallIndigo900_1), SizedBox(height: 12.v), CustomTextFormField(controller: controller.newpasswordController, hintText: "msg".tr, hintStyle: theme.textTheme.labelLarge!, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 12.v, 10.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgLocation, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 48.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: true, contentPadding: EdgeInsets.only(top: 15.v, right: 30.h, bottom: 15.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueTL5, filled: false)])); } 
/// Section Widget
Widget _buildNewPasswordAgain() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_new_password_again".tr, style: CustomTextStyles.titleSmallIndigo900_1), SizedBox(height: 11.v), CustomTextFormField(controller: controller.newpasswordController1, hintText: "msg".tr, hintStyle: theme.textTheme.labelLarge!, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 12.v, 10.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgLocation, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 48.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: true, contentPadding: EdgeInsets.only(top: 15.v, right: 30.h, bottom: 15.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueTL5, filled: false)])); } 
/// Section Widget
Widget _buildSave() { return CustomElevatedButton(height: 64.v, text: "lbl_save".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 50.v), buttonTextStyle: CustomTextStyles.titleMediumOnErrorContainer); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
