import 'controller/notification_activity_controller.dart';import 'package:flutter/material.dart';import 'package:vibra_verve/core/app_export.dart';import 'package:vibra_verve/widgets/app_bar/appbar_leading_image.dart';import 'package:vibra_verve/widgets/app_bar/appbar_subtitle_four.dart';import 'package:vibra_verve/widgets/app_bar/custom_app_bar.dart';class NotificationActivityScreen extends GetWidget<NotificationActivityController> {const NotificationActivityScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [Divider(), _buildActivityList02(), _buildActivityList02(), SizedBox(height: 5.v), _buildActivityList02()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray300, margin: EdgeInsets.only(left: 16.h, top: 26.v, bottom: 28.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitleFour(text: "lbl_activity".tr, margin: EdgeInsets.only(left: 12.h)), styleType: Style.bgFill_1); } 
/// Common widget
Widget _buildActivityList02() { return Container(width: double.maxFinite, padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillOnErrorContainer, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSystemIcon24pxTransaction, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 93.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 291.h, margin: EdgeInsets.only(right: 13.h), child: Text("msg_transaction_nike2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallBold.copyWith(height: 1.50))), SizedBox(height: 10.v), SizedBox(width: 305.h, child: Text("msg_culpa_cillum_consectetur2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall!.copyWith(height: 1.80))), SizedBox(height: 5.v), Text("msg_april_30_2014_1_01".tr, style: CustomTextStyles.bodySmallBlack90010)])))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
